sudo: required
services:
  - docker

before_install:
  - docker build -t czetsuya/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run czetsuya/react-test npm test -- --coverage

after_success:
  - docker build -t czetsuya/multi-docker-react-client:latest ./client
  - docker build -t czetsuya/multi-docker-react-nginx:latest ./nginx
  - docker build -t czetsuya/multi-docker-react-server:latest ./server
  - docker build -t czetsuya/multi-docker-react-worker:latest ./worker
  # Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push
  - docker push czetsuya/multi-docker-react-client:latest
  - docker push czetsuya/multi-docker-react-nginx:latest
  - docker push czetsuya/multi-docker-react-server:latest
  - docker push czetsuya/multi-docker-react-worker:latest

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker-react
  env: MultiDockerReact-env
  bucket_name: elasticbeanstalk-us-east-1-981794644853
  bucket_path: multi-docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY